### ISSUE TITLE
Error When Attempting Token Deposit

### ISSUE THREAD

**Issue by pynchmeister** [0xsequence/erc20-meta-token#33]
I have deployed ERC20Wrapper.sol on Kovan with Remix, and used the setApprovalForAll() function, but when I try to run the deposit function with this [token](https://kovan.etherscan.io/token/0x0331048143015c0784d0f9c723e709314ab87460?a=0xb4d5f5734b49b84a657ee5bb51e0b80645f33263) it always fails with a ```false Transaction mined but execution failed```. I have the tokens in my wallet and I have given some Wei to the deposit function call but I can't quite seem to get it to work, any advice?

Should I be using MetaERC20Wrapper instead of ERC20Wrapper?

**Comment by DeFiSon** [comment]
Hi there
I've the same problem. Depositing gets me a "reverted by EVM" Error
How did you solve this issue?
